// Generates meshes.c from tools/ships.js (the same geometry as the concept art)
// plus the enemy and asteroid meshes defined here.  Run: node tools/genmesh.js
'use strict';
require('./ships.js');
const { SHIPS, DRONE, C } = globalThis.OrcaShips;

function Mesh() { this.v = []; this.f = []; }
Mesh.prototype.vert = function (x, y, z) { this.v.push([x, y, z]); return this.v.length - 1; };
Mesh.prototype.tri = function (a, b, c, col, em) { this.f.push({ i: [a, b, c], col, em: !!em }); };

// Enemy "Stinger": an alien dart, nose along +z like the orcas (the game turns it to face you).
function stinger() {
  const m = new Mesh();
  const hull = [74, 34, 92], blade = [118, 52, 140], glow = [255, 70, 160];
  const nose = m.vert(0, 0, 3.2), tail = m.vert(0, 0, -2.2);
  const top = m.vert(0, 0.8, -0.2), bot = m.vert(0, -0.6, -0.2);
  const l = m.vert(-0.8, 0, 0), r = m.vert(0.8, 0, 0);
  const add = (a, b, c, col, em) => m.tri(a, b, c, col, em);
  // body: an elongated octahedron
  add(nose, top, r, hull); add(nose, l, top, hull); add(nose, r, bot, hull); add(nose, bot, l, hull);
  add(tail, r, top, hull); add(tail, top, l, hull); add(tail, bot, r, hull); add(tail, l, bot, hull);
  // swept blades, each a thin two-sided plate
  for (const s of [1, -1]) {
    const a = m.vert(0.6 * s, 0, 0.8), b = m.vert(0.5 * s, 0, -1.2), c = m.vert(3.2 * s, -0.3, -2.4);
    if (s > 0) { add(a, b, c, blade); add(a, c, b, blade); } else { add(a, c, b, blade); add(a, b, c, blade); }
    // glowing blade tip
    const d = m.vert(3.2 * s, -0.3, -2.4), e = m.vert(2.6 * s, -0.25, -2.2), g = m.vert(2.8 * s, -0.2, -1.6);
    add(d, e, g, glow, true); add(d, g, e, glow, true);
  }
  // glowing eye on the nose
  const e1 = m.vert(-0.25, 0.25, 1.9), e2 = m.vert(0.25, 0.25, 1.9), e3 = m.vert(0, 0.45, 1.2);
  add(e1, e2, e3, glow, true); add(e1, e3, e2, glow, true);
  return m;
}

// Asteroids: jittered icosahedra, a few variants.
function asteroid(seed) {
  const m = new Mesh(); const t = (1 + Math.sqrt(5)) / 2;
  let s = seed; const rnd = () => { s = (s * 16807) % 2147483647; return s / 2147483647; };
  const V = [[-1,t,0],[1,t,0],[-1,-t,0],[1,-t,0],[0,-1,t],[0,1,t],[0,-1,-t],[0,1,-t],[t,0,-1],[t,0,1],[-t,0,-1],[-t,0,1]];
  V.forEach(p => { const l = Math.hypot(...p), k = (0.72 + 0.5 * rnd()) / l; m.vert(p[0] * k, p[1] * k, p[2] * k); });
  [[0,11,5],[0,5,1],[0,1,7],[0,7,10],[0,10,11],[1,5,9],[5,11,4],[11,10,2],[10,7,6],[7,1,8],[3,9,4],[3,4,2],[3,2,6],[3,6,8],[3,8,9],[4,9,5],[2,4,11],[6,2,10],[8,6,7],[9,8,1]]
    .forEach(([a, b, c]) => { const g = 0.8 + 0.4 * rnd(); m.tri(a, c, b, [104 * g, 92 * g, 84 * g]); });
  return m;
}

const sub = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
const cross = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
const f3 = (x) => { let t = (Math.round(x * 1e4) / 1e4 + 0).toString(); if (t === '-0') t = '0'; if (!/[.e]/.test(t)) t += '.0'; return t + 'f'; };

function emit(name, m, scale) {
  const col = (c) => c.map((x) => Math.max(0, Math.min(255, Math.round(x))));
  let r = 0; m.v.forEach((p) => { r = Math.max(r, Math.hypot(...p) * scale); });
  let out = `static const float ${name}_v[${m.v.length}][3] = {\n`;
  out += m.v.map((p) => `  {${p.map((x) => f3(x * scale)).join(', ')}}`).join(',\n') + '\n};\n';
  out += `static const mesh_face_t ${name}_f[${m.f.length}] = {\n`;
  out += m.f.map((f) => {
    const P = f.i.map((i) => m.v[i]); let n = cross(sub(P[1], P[0]), sub(P[2], P[0]));
    const l = Math.hypot(...n) || 1; n = n.map((x) => x / l);
    const c = col(f.col);
    return `  {{${f.i.join(', ')}}, {${n.map(f3).join(', ')}}, ${c[0]}, ${c[1]}, ${c[2]}, ${f.em ? 1 : 0}}`;
  }).join(',\n') + '\n};\n';
  out += `const mesh_t MESH_${name.toUpperCase()} = { ${name}_v, ${name}_f, ${m.v.length}, ${m.f.length}, ${f3(r)} };\n\n`;
  return out;
}

let c = `/* meshes.c — generated by tools/genmesh.js from tools/ships.js. Do not edit. */\n#include "meshes.h"\n\n`;
// Player hulls at half the concept-art scale (about 5.5 units nose to tail).
for (const k of ['apex', 'blackfish', 'matriarch', 'tidebreaker']) c += emit(k, SHIPS[k].mesh, 0.5);
c += emit('manta', DRONE, 0.9);
c += emit('stinger', stinger(), 0.8);
[7, 19, 41].forEach((seed, i) => { c += emit('rock' + i, asteroid(seed), 1.0); });
require('fs').writeFileSync(require('path').join(__dirname, '..', 'meshes.c'), c);
console.log('meshes.c written');
